# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e67c58f7d25d21f29df16633ffa114da5eb242509712602fc16012cf2310ed97d8336622e13b75ba3038889bb6635774678cf313ae97a5e7284493032348200

test:
  secret_key_base: 3bbc35b2f7804ed7df0952327d0da5080c7c0631a3c60f1b32872a0028f7def6fd55c06889d451c5a6ddb1b2ef273b11004df061cf2ef2c7ee5629b63cb14010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
